export const INICIAR_TORNEIO_REQUEST: string = 'INICIAR_TORNEIO_REQUEST';
export const INICIAR_TORNEIO_SUCCESS: string = 'INICIAR_TORNEIO_SUCCESS';
export const INICIAR_TORNEIO_FAILURE: string = 'INICIAR_TORNEIO_FAILURE';