export const GET_LUTADORES_LIST_REQUEST: string = 'GET_LUTADORES_LIST_REQUEST';
export const GET_LUTADORES_LIST_SUCCESS: string = 'GET_LUTADORES_LIST_SUCCESS';
export const GET_LUTADORES_LIST_FAILURE: string = 'GET_LUTADORES_LIST_FAILURE';

export const CARREGAR_LUTADORES_REQUEST: string = 'CARREGAR_LUTADORES_REQUEST';
export const CARREGAR_LUTADORES_SUCCESS: string = 'CARREGAR_LUTADORES_SUCCESS';
export const CARREGAR_LUTADORES_FAILURE: string = 'CARREGAR_LUTADORES_FAILURE';